networks:
  # The presence of these objects is sufficient to define them
  expense: {}

volumes:
  mysql:

services:   
  backend:
    image: vishnupriyadh/backend:1.0.0
    command: sh -c "sleep 500 && node /opt/backend/index.js" # add 5 sec delay for backend to run as sometimes
                                                             # backend runs faster when mysql is still running
    networks:
      - expense
    container_name: backend
    # volumes:  - Volumes not required for backend as backend is stateless
    depends_on:
      - mysql

 # docker run -d --name mysql --v mysql-data:/var/lib/mysql --network expense mysql:1.0.0   
  mysql:
    image: vishnupriyadh/mysql:1.0.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql # this the location/directory where mysql stores the data in OS

    
  frontend:
    image: vishnupriyadh/frontend:1.0.0
    ports:
      - 80:80
    networks:
      - expense
    container_name: frontend
    # volumes:  - Volumes not required for backend as backend is stateless
    depends_on:
      - backend

